<ips:template parameters="$member, $results, $pagination" />

<div data-baseurl="{url="app=core&module=members&controller=profile&do=content&id={$member->member_id}&page=1" seoTemplate="profile_content" seoTitle="$member->members_seo_name"}" data-resort="listResort" data-tableid="topics"> <!-- data-controller="core.global.core.table" -->
	{{if $pagination}}
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
			<div data-role="tablePagination">
				{$pagination|raw}
			</div>
		</div>
	{{endif}}
	<ol class='ipsDataList ipsDataList_large cSearchActivity ipsStream ipsPad' data-role="tableRows">
		{{foreach $results as $activity}}
			{$activity->html()|raw}
		{{endforeach}}
	</ol>
	{{if $pagination}}
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
			{$pagination|raw}
		</div>
	{{endif}}
</div>