<ips:template parameters="$date, $events, $venue" />

<div class='ipsGrid ipsGrid_collapsePhone ipsPager cCalendarNav ipsSpacer_bottom' data-ipsSticky data-ipsSticky-disableIn='phone'>
	<div class='ipsGrid_span3 ipsType_left ipsPager_prev'>
		<a href="{{if $venue}}{url="app=calendar&module=calendar&controller=venue&id={$venue->_id}&y={$date->lastMonth('year')}&m={$date->lastMonth('mon')}" seoTemplate="calendar_venue" seoTitle="$venue->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=venue&y={$date->lastMonth('year')}&m={$date->lastMonth('mon')}" seoTemplate="calendar_venue"}{{endif}}" title='{lang="cal_month_stream_title" sprintf="$date->lastMonth('monthName'), $date->lastMonth('year')"}' rel='prev nofollow' data-action='changeView'>
			<span class='ipsPager_type ipsType_normal'>{$date->lastMonth('monthName')}</span>
			<span class='ipsPager_title ipsType_light'>{$date->lastMonth('year')}</span>
		</a>
	</div>
	<div class='ipsGrid_span6 ipsType_center ipsPad' data-role='calendarNav'>
		<h1 class='ipsType_pageTitle ipsType_center'>{lang="cal_month_title" sprintf="$date->monthName, $date->year"}</h1>

	</div>
	<div class='ipsGrid_span3 ipsType_right ipsPager_next'>
		<a href="{{if $venue}}{url="app=calendar&module=calendar&controller=venue&id={$venue->_id}&y={$date->nextMonth('year')}&m={$date->nextMonth('mon')}" seoTemplate="calendar_venue" seoTitle="$venue->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=venue&y={$date->nextMonth('year')}&m={$date->nextMonth('mon')}" seoTemplate="calendar_venue"}{{endif}}" title='{lang="cal_month_stream_title" sprintf="$date->nextMonth('monthName'), $date->nextMonth('year')"}' rel='next nofollow' data-action='changeView'>
			<span class='ipsPager_type ipsType_normal'>{$date->nextMonth('monthName')}</span>
			<span class='ipsPager_title ipsType_light'>{$date->nextMonth('year')}</span>
		</a>
	</div>
</div>

<section class='ipsAreaBackground ipsPad' id='venueStream'>
	{{if count($events) }}
		<div>
			<div class='ipsList_reset'>
				{{foreach $events as $event}}
					<div>
						{template="eventStreamBlock" app="calendar" group="view" params="$event, $date, TRUE, array( 240, 185 ), TRUE"}
					</div>
				{{endforeach}}
			</div>
		</div>
	{{else}}
		<div class='ipsType_light ipsType_large'>{lang="no_events_month"}</div>
	{{endif}}
</section>