<ips:template parameters="$forms, $error" />
{{if !\IPS\Request::i()->isAjax()}}
	<div class=''>
		<br>
		<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang='sign_in_short'}</h1>
		{{if \IPS\Settings::i()->allow_reg}}
			<p class='ipsType_reset ipsType_large ipsType_center ipsType_light'>{lang="dont_have_an_account"} <a href='{url="app=core&module=system&controller=register" seoTemplate="register" protocol="\IPS\Settings::i()->logins_over_https"}'>{lang="sign_up"}</a>.</p>
		{{endif}}
		<br>
{{endif}}

	{{if count ( $forms ) > 1}}
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_fluid'>
	{{endif}}
				<div class='ipsBox ipsForm_fullWidth cLogin {{if count ( $forms ) == 1}}cLogin_noSocial ipsPad_double ipsPos_center{{else}}ipsPad{{endif}}'>
					{{if $error !== NULL}}
						{template="message" group="global" location="global" params="$error, 'error'"}
						<br>
					{{endif}}
					{{foreach $forms as $k => $form}}
						{{if $k === '_standard'}}
							{$form|raw}
						{{endif}}
					{{endforeach}}
				</div>
	{{if count ( $forms ) > 1}}
			</div>
			<div class='ipsColumn ipsColumn_veryWide ipsBox'>
				<div class='ipsPad'>
					<h2 class='ipsType_sectionHead'>{lang='sign_in_faster'}</h2>
					{{if count ( $forms ) > 2}}
						<p class='ipsType_normal ipsType_reset ipsType_light'>{lang='sign_in_connect'}</p>
					{{endif}}
					<br>
					{{foreach $forms as $k => $form}}
						{{if $k !== '_standard'}}
							<div class='cLogin_social'>{$form|raw}</div>
						{{endif}}
					{{endforeach}}
				</div>
			</div>
		</div>
	{{endif}}
	
{{if !\IPS\Request::i()->isAjax()}}
</div>
{{endif}}