<ips:template parameters="$item, $login, $isReview=FALSE" />

{{$ref = base64_encode( $item->url() . '#replyForm' );}}
{{if \IPS\Settings::i()->allow_reg}}
	<div class='ipsType_center ipsPad cGuestTeaser'>
		{{if $isReview}}
			<h2 class='ipsType_pageTitle'>{lang="teaser_review_title_reg"}</h2>
			<p class='ipsType_light ipsType_normal ipsType_reset'>{lang="teaser_review_desc_reg"}</p>
		{{else}}
			<h2 class='ipsType_pageTitle'>{lang="teaser_title_reg"}</h2>
			<p class='ipsType_light ipsType_normal ipsType_reset'>{lang="teaser_desc_reg"}</p>
		{{endif}}

		<div class='ipsBox ipsPad ipsSpacer_top'>
			<div class='ipsGrid ipsGrid_collapsePhone'>
				<div class='ipsGrid_span6 cGuestTeaser_left'>
					<h2 class='ipsType_sectionHead'>{lang="teaser_account"}</h2>
					<p class='ipsType_normal ipsType_reset ipsType_light ipsSpacer_bottom'>{lang="teaser_account_desc"}</p>
					<a href='{url="app=core&module=system&controller=register" seoTemplate="register" protocol="\IPS\Settings::i()->logins_over_https"}' class='ipsButton ipsButton_primary ipsButton_small'>{lang="teaser_account_button"}</a>
				</div>
				<div class='ipsGrid_span6 cGuestTeaser_right'>
					<h2 class='ipsType_sectionHead'>{lang="teaser_signin"}</h2>
					<p class='ipsType_normal ipsType_reset ipsType_light ipsSpacer_bottom'>{lang="teaser_signin_desc"}</p>
					<a href='{url="app=core&module=system&controller=login&ref={$ref}" seoTemplate="login" protocol="\IPS\Settings::i()->logins_over_https"}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title="{lang="teaser_signin_button"}" class='ipsButton ipsButton_primary ipsButton_small'>{lang="teaser_signin_button"}</a>
				</div>
			</div>
			{{if count ( $login->forms( FALSE, TRUE ) ) > 1}}
				<hr class='ipsHr'>
				<ul class='ipsList_inline ipsList_noSpacing'>
					{{foreach $login->forms( FALSE, TRUE ) as $k => $form}}
					{{if $k !== '_standard'}}
					<li class='ipsType_center ipsPos_center cGuestTeaser_social'>
						{$form|raw}
					</li>
					{{endif}}
					{{endforeach}}
				</ul>
			{{endif}}
		</div>
	</div>
{{else}}
	<div class='ipsType_center ipsPad'>
		<h2 class='ipsType_pageTitle'>{lang="teaser_title_noreg"}</h2>
		<p class='ipsType_light ipsType_normal ipsType_reset'>{lang="teaser_desc_noreg"}</p>
		<br>
		<br>
		<a href='{url="app=core&module=system&controller=login&ref={$ref}" seoTemplate="login"}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title="{lang="teaser_signin_button"}" class='ipsButton ipsButton_alternate ipsButton_large'>{lang="teaser_signin_button"}</a>
	</div>
{{endif}}
