<ips:template parameters="$object, $promote=NULL" />
{{$class = get_class($object);}}
{{$column = $class::$databaseColumnId;}}
{{$id = $object->$column;}}
{{if $promote and $promote->id}}
	<a href='{url="app=core&module=promote&controller=promote&class={$class}&id={$id}&promote_id={$promote->id}&repromote=1" seoTemplate="promote"}' data-ipsDialog-flashMessage="{lang="promote_flash_msg"}" data-ipsDialog-fixed data-ipsDialog-size='large' data-ipsDialog-flashMessageTimeout="5" data-ipsDialog data-ipsDialog-remoteSubmit="true" data-ipsDialog-title="{lang="promote_social_button"}" class="ipsType_blendLinks ipsType_noUnderline">{lang="promote_social_button_repromote"}</a>
{{else}}
	<a href='{url="app=core&module=promote&controller=promote&class={$class}&id={$id}" seoTemplate="promote"}' data-ipsDialog-flashMessage="{lang="promote_flash_msg"}" data-ipsDialog-flashMessageTimeout="5" data-ipsDialog-fixed data-ipsDialog-size='large' data-ipsDialog data-ipsDialog-remoteSubmit="true" data-ipsDialog-title="{lang="promote_social_button"}" class="ipsType_blendLinks ipsType_noUnderline">{lang="promote_social_button"}</a>
{{endif}}

