<ips:template parameters="$event" />
<div class='cEvent_details'>
	<h1 class='ipsType_pageTitle ipsContained_container ipsTruncate ipsTruncate_line'>
		{{if $event->prefix()}}
			<span>{template="prefix" group="global" app="core" params="$event->prefix( TRUE ), $event->prefix()"}</span>
		{{endif}}

		{{if $event->locked()}}<span><i class='fa fa-lock'></i></span> {{endif}}

		{{if $event->mapped('pinned') || $event->mapped('featured') || $event->hidden() === -1 || $event->hidden() === 1 || $event->hidden() === -2}}
			<span>
				{{if $event->hidden() === -1}}
					<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{$event->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
				{{elseif $event->hidden() === -2}}
					<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{$event->deletedBlurb()}'><i class='fa fa-trash'></i></span></span>
				{{elseif $event->hidden() === 1}}
					<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
				{{endif}}
				{{if $event->mapped('pinned')}}
					<span class="ipsBadge ipsBadge_icon ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
				{{endif}}
				{{if $event->mapped('featured')}}
					<span class="ipsBadge ipsBadge_icon ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
				{{endif}}
			</span>
		{{endif}}
		{{if $event->canEdit()}}
			<span class='ipsType_break ipsContained' data-controller="core.front.core.moderation">
				<span data-role="editableTitle" title='{lang="click_hold_edit"}' class='ipsPageHead_barText'>{$event->title}</span>
			</span>
		{{else}}
			<span class='ipsType_break ipsContained'>
				<span class='ipsPageHead_barText'>{$event->title}</span>
			</span>
		{{endif}}
	</h1>
	<p class='ipsType_normal ipsType_reset ipsPageHead_barText_small'>
		<time content='{expression="$event->_start_date->format( 'Y-m-d' )"}'>
			{{if $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )}}
				{$event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->calendarDate()}{{if !$event->all_day}}, {$event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->localeTime( FALSE )} {{endif}}
			{{else}}
				{$event->lastOccurrence( 'startDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'startDate' )->localeTime( FALSE )} {{endif}}
			{{endif}}
		</time>
		{{if $event->_end_date}}
			&nbsp;&nbsp;<i class='fa fa-arrow-circle-right ipsType_large ipsType_light'></i>&nbsp;&nbsp;
			<time content='{expression="$event->_end_date->format( 'Y-m-d' )"}'>
				{{$sameDay = !( ($event->_start_date->mday != $event->_end_date->mday) or ($event->_start_date->mon != $event->_end_date->mon) or ($event->_start_date->year != $event->_end_date->year) );}}
				{{if $event->nextOccurrence( $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: \IPS\calendar\Date::getDate(), 'endDate' )}}
				{{if !$sameDay}}{$event->nextOccurrence( $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: \IPS\calendar\Date::getDate(), 'endDate' )->calendarDate()}{{endif}}{{if !$event->all_day}}{{if !$sameDay}}, {{endif}}{$event->nextOccurrence( $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: \IPS\calendar\Date::getDate(), 'endDate' )->localeTime( FALSE )}{{endif}}
				{{else}}
					{$event->lastOccurrence( 'endDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'endDate' )->localeTime( FALSE )}{{endif}}
				{{endif}}
			</time>
		{{endif}}
	</p>
</div>