<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm id='elPromoteDialogContent'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}

	<div data-role='promoteDialogBody' class='ipsPad'>
		<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_collapseTablet'>
			<div class='ipsColumn ipsColumn_fluid'>
				<ul class='ipsList_reset'>
					{{foreach $elements['promote_links'] as $id => $input}}
						{{if is_object( $input ) }}
							{$input->rowHtml($form)|raw}
						{{else}}
							{$input|raw}
						{{endif}}
					{{endforeach}}
				</ul>
				<ul class='ipsList_reset'>
					{{foreach $elements['promote_content'] as $id => $input}}
						{{if is_object( $input ) }}
							{$input->rowHtml($form)|raw}
						{{else}}
							{$input|raw}
						{{endif}}
					{{endforeach}}
				</ul>
			</div>
			<div class='ipsColumn ipsColumn_veryWide'>
				<div class='ipsPad ipsAreaBackground_light'>
					{{foreach $elements['promote_meta'] as $id => $input}}
						<h3 class='ipsType_reset ipsType_normal ipsSpacer_bottom'>{lang="promote_meta_{$id}"}</h3>
						<ul class='ipsList_reset'>
							{{if is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						</ul>
					{{endforeach}}
				</div>
			</div>
		</div>

		<div id='elSchedulePromote_menu' class='ipsMenu ipsMenu_auto ipsPad ipsHide'>
			<ul class='ipsList_reset'>
				{{foreach $elements['promote_schedule'] as $id => $input}}
					{{if is_object( $input ) }}
						{$input->rowHtml($form)|raw}
					{{else}}
						{$input|raw}
					{{endif}}
				{{endforeach}}
			</ul>
		</div>
	</div>

	<ul class="ipsPad ipsToolList ipsToolList_horizontal ipsList_reset ipsClearfix ipsAreaBackground cPromoteSubmit">
		{{foreach $actionButtons as $button}}
			<li>{$button|raw}</li>
		{{endforeach}}

		<li>
			<a href='#' class='ipsButton ipsButton_veryLight ipsButton_fullWidth' id='elSchedulePromote' data-ipsMenu data-ipsMenu-appendTo='#elPromoteDialogContent'><i class='fa fa-clock-o'></i> {lang="promote_schedule_dialog"} <span data-role="promoteSchedule"></span> <i class='fa fa-caret-down'></i></a>
		</li>
	</ul>
</form>