<ips:template parameters="$club, $members" />
<ol class='ipsAreaBackground ipsList_reset ipsPad ipsGrid ipsGrid_collapsePhone ipsClear' data-ipsGrid data-ipsGrid-equalHeights='row' data-ipsGrid-minItemSize='170' data-ipsGrid-maxItemSize='400'>
{{if count( $members )}}
	{{foreach $members as $member}}
		<li class='ipsGrid_span2 ipsClearfix ipsMemberCard'>
			{template="userPhotoFromData" group="global" app="core" params="$member['core_members']['member_id'], $member['core_members']['name'], $member['core_members']['members_seo_name'], \IPS\Member::photoUrl( $member['core_members'] ), 'medium', 'ipsMemberCard_photo'"}

			<h3 class='ipsType_sectionHead ipsMemberCard_name'>
				{$member['core_members']['name']}
			</h3>

			{{if $club->owner and $member['core_members']['member_id'] === $club->owner->member_id}}
				<span class="ipsBadge ipsBadge_positive cClubMemberStatus">{lang="club_owner"}</span>
			{{elseif $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_LEADER}}
				<span class="ipsBadge ipsBadge_positive cClubMemberStatus">{lang="club_leader"}</span>
			{{elseif $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_MODERATOR}}
				<span class="ipsBadge ipsBadge_intermediary cClubMemberStatus">{lang="club_moderator"}</span>
			{{endif}}

			{{if $club->isLeader() and !in_array( $member['core_clubs_memberships']['status'], array( \IPS\Member\Club::STATUS_REQUESTED, \IPS\Member\Club::STATUS_INVITED ) ) and ( !$club->owner or $member['core_members']['member_id'] !== $club->owner->member_id )}}
				<a href="#elMember{$member['core_members']['member_id']}Menu_menu" id="elMember{$member['core_members']['member_id']}Menu" data-ipsMenu class="ipsButton ipsButton_verySmall ipsButton_light ipsButton_narrow ipsMemberCard_controls"><i class="fa fa-cog"></i> <i class='fa fa-angle-down'></i></a>
				<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="elMember{$member['core_members']['member_id']}Menu_menu">
					{{if in_array( $member['core_clubs_memberships']['status'], array( \IPS\Member\Club::STATUS_DECLINED, \IPS\Member\Club::STATUS_BANNED ) )}}
						<li class="ipsMenu_item" ><a href="{$club->url()->setQueryString( array( 'do' => 'reInvite', 'member' => $member['core_members']['member_id'] ) )->csrf()}" data-confirm>{lang="club_banned_invite"}</a></li>
					{{else}}
						{{if $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_LEADER}}
							<li class="ipsMenu_item" ><a href="{$club->url()->setQueryString( array( 'do' => 'demoteLeader', 'member' => $member['core_members']['member_id'] ) )->csrf()}" data-confirm>{lang="club_demote_leader"}</a></li>
						{{else}}
							<li class="ipsMenu_item" ><a href="{$club->url()->setQueryString( array( 'do' => 'makeLeader', 'member' => $member['core_members']['member_id'] ) )->csrf()}" data-confirm data-confirmSubMessage="{lang="club_make_leader_confirm"}">{lang="club_make_leader"}</a></li>
						{{endif}}
						{{if $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_MODERATOR}}
							<li class="ipsMenu_item" ><a href="{$club->url()->setQueryString( array( 'do' => 'demoteModerator', 'member' => $member['core_members']['member_id'] ) )->csrf()}" data-confirm>{lang="club_demote_moderator"}</a></li>
						{{else}}
							<li class="ipsMenu_item" ><a href="{$club->url()->setQueryString( array( 'do' => 'makeModerator', 'member' => $member['core_members']['member_id'] ) )->csrf()}" data-confirm data-confirmSubMessage="{lang="club_make_moderator_confirm"}">{lang="club_make_moderator"}</a></li>
						{{endif}}
						<li class="ipsMenu_item" ><a href="{$club->url()->setQueryString( array( 'do' => 'removeMember', 'member' => $member['core_members']['member_id'] ) )->csrf()}" data-confirm data-confirmSubMessage="{lang="club_remove_member_confirm"}">{lang="club_remove_member"}</a></li>
					{{endif}}
				</ul>
			{{endif}}

			<hr class='ipsHr ipsHr_small'>

			<h4 class='ipsType_minorHeading ipsType_unbold'>
				{{if $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_REQUESTED}}
					{lang="club_date_joined_request"}
				{{elseif $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_INVITED}}
					{lang="club_date_joined_invite"}
				{{else}}
					{lang="club_date_joined"}
				{{endif}}
			</h4>
			<p class='ipsType_reset ipsTruncate ipsTruncate_line'>
				{{if $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_REQUESTED}}
					{expression="\IPS\DateTime::ts( $member['core_clubs_memberships']['joined'] )->relative()"}
				{{elseif $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_INVITED}}
					{expression="\IPS\DateTime::ts( $member['core_clubs_memberships']['joined'] )->relative()"}
				{{else}}
					{expression="\IPS\DateTime::ts( $member['core_clubs_memberships']['joined'] )->relative()"}
				{{endif}}
			</p>

			{{if $club->isLeader()}}
				{{if ( $member['added_by']['name'] or $member['invited_by']['name'] )}}
					<hr class='ipsHr ipsHr_small'>
					<p class='ipsType_reset ipsContained ipsType_break'>
						{{if in_array( $member['core_clubs_memberships']['status'], array( \IPS\Member\Club::STATUS_DECLINED, \IPS\Member\Club::STATUS_BANNED ) )}}
							{{if $member['added_by']['name']}}
								{{if $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_BANNED}}
									{lang="club_banned_by" sprintf="$member['added_by']['name']"}
								{{else}}
									{lang="club_declined_by" sprintf="$member['added_by']['name']"}
								{{endif}}
							{{else}}
								{{if $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_BANNED}}
									{lang="club_banned"}
								{{else}}
									{lang="club_declined"}
								{{endif}}
							{{endif}}
						{{else}}
							{{if $member['invited_by']['name']}}
								{lang="club_invited_by" sprintf="$member['invited_by']['name']"}
							{{else}}
								{lang="club_added_by" sprintf="$member['added_by']['name']"}
							{{endif}}
						{{endif}}
					</p>
				{{endif}}
			{{endif}}


			{{if $club->isLeader() && $member['core_clubs_memberships']['status'] === \IPS\Member\Club::STATUS_REQUESTED}}
				<hr class='ipsHr ipsHr_small'>
				<ul class='ipsGrid ipsMemberCard_buttons'>
					<li class='ipsGrid_span6'>
						<a href="{$club->url()->setQueryString( array( 'do' => 'acceptRequest', 'member' => $member['core_members']['member_id'] ) )->csrf()}" class="ipsButton ipsButton_small ipsButton_positive ipsButton_fullWidth" data-ipsTooltip title='{lang="club_accept_request"}' data-action='requestApprove'><i class='fa fa-check'></i></a>
					</li>
					<li class='ipsGrid_span6'>
						<a href="{$club->url()->setQueryString( array( 'do' => 'declineRequest', 'member' => $member['core_members']['member_id'] ) )->csrf()}" class="ipsButton ipsButton_small ipsButton_negative ipsButton_fullWidth" data-ipsTooltip title='{lang="club_decline_request"}' data-action='requestDecline'><i class='fa fa-times'></i></a>
					</li>
				</ul>
			{{endif}}
		</li>
	{{endforeach}}
{{else}}
	<li>{lang="no_results"}</li>
{{endif}}
</ol>