<ips:template parameters="$club, $memberStatus" />

{{if $memberStatus['status'] == $club::STATUS_INVITED && $club->canJoin()}}
    {{if $memberStatus['invited_by']}}
    	{{$invitedBy = \IPS\Member::load( $memberStatus['invited_by'] );}}
    	<div class='ipsBox ipsPad'>
	    	<div class='ipsColumns ipsColumns_collapsePhone'>
	    		<div class='ipsColumn ipsColumn_fluid'>
					<div class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_tiny'>
						{template="userPhoto" group="global" app="core" params="$invitedBy, 'tiny'"}
						<div class='ipsType_medium'>
							<h3 class='ipsType_reset ipsType_large'>{lang="club_youre_invited"}</h3>
							<p class='ipsType_reset ipsType_medium'>
								{lang="club_youre_invited_desc" sprintf="$invitedBy->name"}
							</p>
						</div>
					</div>
				</div>
				<div class='ipsColumn ipsColumn_narrow'>
					<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_positive" href="{$club->url()->setQueryString('do', 'join')->csrf()}">
						{lang="club_join"}
					</a>
				</div>
			</div>
		</div>
		<hr class='ipsHr'>
    {{endif}}
{{elseif $memberStatus['status'] == \IPS\Member\Club::STATUS_BANNED}}
	<div class='ipsBox ipsPad ipsSpacer_bottom'>
		<div class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_tiny cClubStatus'>
			<i class='fa fa-times ipsPos_left ipsType_large'></i>
			<div>
				<h3 class='ipsType_reset ipsType_large'>{lang="club_banned_title"}</h3>
				<p class='ipsType_reset ipsType_medium'>
					{lang="club_banned_desc"}
				</p>
			</div>
		</div>
	</div>
{{elseif !$club->canRead()}}
	<div class='ipsBox ipsPad ipsSpacer_bottom'>
		{{if $memberStatus['status'] === $club::STATUS_REQUESTED}}
			<div class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_tiny cClubStatus'>
				<i class='fa fa-clock-o ipsPos_left ipsType_large'></i>
				<div>
					<h3 class='ipsType_reset ipsType_large'>{lang="club_requested_title"}</h3>
					<p class='ipsType_reset ipsType_medium'>
						{lang="club_requested_desc"}
					</p>
				</div>
			</div>
		{{elseif $memberStatus === \IPS\Member\Club::STATUS_DECLINED}}
			<div class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_tiny cClubStatus'>
				<i class='fa fa-times ipsPos_left ipsType_large'></i>
				<div>
					<h3 class='ipsType_reset ipsType_large'>{lang="club_denied_title"}</h3>
					<p class='ipsType_reset ipsType_medium'>
						{lang="club_denied_desc"}
					</p>
				</div>
			</div>
		{{else}}
			<div class='ipsColumns ipsColumns_collapsePhone'>
	    		<div class='ipsColumn ipsColumn_fluid'>
					<div class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_tiny cClubStatus'>
						<i class='fa fa-lock ipsPos_left ipsType_large'></i>
						<div>
							<h3 class='ipsType_reset ipsType_large'>{lang="club_closed_title"}</h3>
							<p class='ipsType_reset ipsType_medium'>
								{lang="club_closed_desc"}
							</p>
							{{if $club->about}}
								<h3 class='ipsType_minorHeading ipsSpacer_top'>{lang="club_about_this_club"}</h3>
								<div class='ipsType_richText ipsType_medium'>
									{$club->about}
								</div>
							{{endif}}
						</div>
					</div>
				</div>
				<div class='ipsColumn ipsColumn_narrow'>
					<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_positive" href="{$club->url()->setQueryString('do', 'join')->csrf()}">
						{lang="club_join"}
					</a>
				</div>
			</div>
		{{endif}}
	</div>
{{endif}}